import os

from datetime import datetime

import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Connection, Engine
from dotenv import load_dotenv


load_dotenv()

_engine: Engine | None = None
_engine_url: str | None = None


def _get_engine() -> Engine:
    global _engine, _engine_url

    database_url = os.getenv("DATABASE_URL")

    if not database_url:
        raise RuntimeError(
            "DATABASE_URL is required to connect to PostgreSQL."
        )

    if _engine is None or _engine_url != database_url:
        if _engine is not None:
            _engine.dispose()
        _engine = create_engine(
            database_url,
            pool_pre_ping=True
        )
        _engine_url = database_url

    return _engine


def get_connection() -> Connection:
    """Create a PostgreSQL connection using DATABASE_URL."""

    return _get_engine().connect()


def normalize_analysis_date(analysis_date):
    """Convert any valid date-like value into YYYY-MM-DD."""

    if analysis_date is None:
        return None

    try:
        return pd.to_datetime(analysis_date).strftime("%Y-%m-%d")
    except (TypeError, ValueError):
        return str(analysis_date)


def _native_value(value):
    """Convert NumPy scalar values to native Python database parameters."""

    if hasattr(value, "item"):
        return value.item()
    return value


def initialize_database():
    """Create the PostgreSQL tables and indexes used by the monitor."""

    statements = [
        """
        CREATE TABLE IF NOT EXISTS analysis_runs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            analysis_time TEXT NOT NULL,
            analysis_date TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS metric_results (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES analysis_runs(id),
            metric TEXT NOT NULL,
            current_value DOUBLE PRECISION,
            percentage_change DOUBLE PRECISION,
            baseline_deviation DOUBLE PRECISION,
            z_score DOUBLE PRECISION,
            anomaly_score DOUBLE PRECISION,
            severity TEXT,
            business_impact TEXT,
            priority TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS business_findings (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES analysis_runs(id),
            finding_type TEXT,
            severity TEXT,
            observation TEXT,
            possible_implication TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS alerts (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id INTEGER NOT NULL REFERENCES analysis_runs(id),
            metric TEXT NOT NULL,
            priority TEXT,
            severity TEXT,
            percentage_change DOUBLE PRECISION,
            analysis_date TEXT,
            sent_at TEXT NOT NULL
        )
        """,
    ]

    with _get_engine().begin() as connection:
        for statement in statements:
            connection.execute(text(statement))

        alert_columns = connection.execute(
            text(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = 'alerts'
                """
            )
        ).scalars().all()

        if "analysis_date" not in alert_columns:
            connection.execute(
                text(
                    "ALTER TABLE alerts ADD COLUMN analysis_date TEXT"
                )
            )

        connection.execute(
            text(
                """
                CREATE INDEX IF NOT EXISTS
                idx_metric_results_run_id
                ON metric_results(run_id)
                """
            )
        )
        connection.execute(
            text(
                """
                CREATE INDEX IF NOT EXISTS
                idx_business_findings_run_id
                ON business_findings(run_id)
                """
            )
        )
        connection.execute(
            text(
                """
                CREATE OR REPLACE VIEW powerbi_metric_results AS
                SELECT
                    mr.id,
                    mr.run_id,
                    ar.analysis_date,
                    ar.analysis_time,
                    mr.metric,
                    mr.current_value,
                    mr.percentage_change,
                    mr.baseline_deviation,
                    mr.z_score,
                    mr.anomaly_score,
                    mr.severity,
                    mr.business_impact,
                    mr.priority
                FROM metric_results mr
                JOIN analysis_runs ar ON ar.id = mr.run_id
                """
            )
        )


def remove_duplicate_alerts():
    """Keep the oldest alert per metric, priority, and analysis date."""

    initialize_database()

    with _get_engine().begin() as connection:
        result = connection.execute(
            text(
                """
                DELETE FROM alerts
                WHERE analysis_date IS NOT NULL
                  AND id NOT IN (
                      SELECT MIN(id)
                      FROM alerts
                      WHERE analysis_date IS NOT NULL
                      GROUP BY metric, priority, analysis_date
                  )
                """
            )
        )
        return result.rowcount


def create_alert_unique_index():
    """Create the database constraint preserving alert deduplication."""

    initialize_database()
    remove_duplicate_alerts()

    with _get_engine().begin() as connection:
        connection.execute(
            text(
                """
                CREATE UNIQUE INDEX IF NOT EXISTS idx_alert_unique
                ON alerts(metric, priority, analysis_date)
                """
            )
        )


def save_analysis(
    results,
    business_findings,
    analysis_date=None
):
    """Save one analysis run and return its run ID."""

    initialize_database()
    analysis_time = datetime.now().isoformat(timespec="seconds")
    analysis_date_value = normalize_analysis_date(analysis_date)

    with _get_engine().begin() as connection:
        run_id = connection.execute(
            text(
                """
                INSERT INTO analysis_runs (analysis_time, analysis_date)
                VALUES (:analysis_time, :analysis_date)
                RETURNING id
                """
            ),
            {
                "analysis_time": analysis_time,
                "analysis_date": analysis_date_value,
            }
        ).scalar_one()

        for result in results:
            connection.execute(
                text(
                    """
                    INSERT INTO metric_results (
                        run_id, metric, current_value, percentage_change,
                        baseline_deviation, z_score, anomaly_score, severity,
                        business_impact, priority
                    )
                    VALUES (
                        :run_id, :metric, :current_value, :percentage_change,
                        :baseline_deviation, :z_score, :anomaly_score,
                        :severity, :business_impact, :priority
                    )
                    """
                ),
                {
                    "run_id": run_id,
                    "metric": result.get("metric"),
                    "current_value": _native_value(
                        result.get("current_value")
                    ),
                    "percentage_change": _native_value(
                        result.get("percentage_change")
                    ),
                    "baseline_deviation": _native_value(
                        result.get("baseline_deviation")
                    ),
                    "z_score": _native_value(
                        result.get("z_score")
                    ),
                    "anomaly_score": _native_value(
                        result.get("score")
                    ),
                    "severity": result.get("severity"),
                    "business_impact": result.get("business_impact"),
                    "priority": result.get("priority"),
                }
            )

        for finding in business_findings:
            connection.execute(
                text(
                    """
                    INSERT INTO business_findings (
                        run_id, finding_type, severity, observation,
                        possible_implication
                    )
                    VALUES (
                        :run_id, :finding_type, :severity, :observation,
                        :possible_implication
                    )
                    """
                ),
                {
                    "run_id": run_id,
                    "finding_type": finding.get("type"),
                    "severity": finding.get("severity"),
                    "observation": finding.get("observation"),
                    "possible_implication": finding.get(
                        "possible_implication"
                    ),
                }
            )

    return run_id


def get_metric_history(metric=None):
    """Return historical metric analysis as a DataFrame."""

    initialize_database()
    query = """
        SELECT
            ar.analysis_date,
            ar.analysis_time,
            mr.metric,
            mr.current_value,
            mr.percentage_change,
            mr.baseline_deviation,
            mr.z_score,
            mr.anomaly_score,
            mr.severity,
            mr.business_impact,
            mr.priority
        FROM metric_results mr
        JOIN analysis_runs ar ON mr.run_id = ar.id
    """
    parameters = {}

    if metric is not None:
        query += " WHERE mr.metric = :metric"
        parameters["metric"] = metric

    query += " ORDER BY ar.analysis_time ASC"

    with _get_engine().connect() as connection:
        return pd.read_sql_query(
            text(query),
            connection,
            params=parameters
        )


def get_run_history():
    """Return historical analysis runs as a DataFrame."""

    initialize_database()
    query = """
        SELECT
            ar.id,
            ar.analysis_time,
            ar.analysis_date,
            COUNT(mr.id) AS metrics_analyzed,
            SUM(CASE WHEN mr.severity = 'CRITICAL' THEN 1 ELSE 0 END)
                AS critical_count,
            SUM(CASE WHEN mr.severity = 'WARNING' THEN 1 ELSE 0 END)
                AS warning_count
        FROM analysis_runs ar
        LEFT JOIN metric_results mr ON ar.id = mr.run_id
        GROUP BY ar.id, ar.analysis_time, ar.analysis_date
        ORDER BY ar.analysis_time DESC
    """

    with _get_engine().connect() as connection:
        return pd.read_sql_query(text(query), connection)


def alert_already_sent(
    metric,
    priority,
    analysis_date
):
    """Check whether an alert exists for the deduplication key."""

    if analysis_date is None:
        return False

    initialize_database()
    with _get_engine().connect() as connection:
        existing = connection.execute(
            text(
                """
                SELECT 1
                FROM alerts
                WHERE metric = :metric
                  AND priority = :priority
                  AND analysis_date = :analysis_date
                LIMIT 1
                """
            ),
            {
                "metric": str(metric),
                "priority": str(priority),
                "analysis_date": normalize_analysis_date(
                    analysis_date
                ),
            }
        ).first()

    return existing is not None


def save_alert(
    run_id,
    metric,
    priority,
    severity,
    percentage_change,
    analysis_date
):
    """
    Save an email alert, returning False for an existing deduplication key.
    """

    if analysis_date is None:
        raise ValueError("analysis_date cannot be None.")

    create_alert_unique_index()
    with _get_engine().begin() as connection:
        result = connection.execute(
            text(
                """
                INSERT INTO alerts (
                    run_id, metric, priority, severity, percentage_change,
                    analysis_date, sent_at
                )
                VALUES (
                    :run_id, :metric, :priority, :severity,
                    :percentage_change, :analysis_date, :sent_at
                )
                ON CONFLICT (metric, priority, analysis_date) DO NOTHING
                """
            ),
            {
                "run_id": run_id,
                "metric": str(metric),
                "priority": str(priority),
                "severity": str(severity),
                "percentage_change": _native_value(
                    percentage_change
                ),
                "analysis_date": normalize_analysis_date(analysis_date),
                "sent_at": datetime.now().isoformat(timespec="seconds"),
            }
        )
        return result.rowcount == 1


def get_alert_history():
    """Return all previously sent email alerts as a DataFrame."""

    initialize_database()
    query = """
        SELECT
            a.id,
            a.run_id,
            a.metric,
            a.priority,
            a.severity,
            a.percentage_change,
            a.analysis_date,
            a.sent_at
        FROM alerts a
        ORDER BY a.sent_at DESC
    """

    with _get_engine().connect() as connection:
        return pd.read_sql_query(text(query), connection)


def database_health_check():
    """Verify that PostgreSQL is accessible and operational."""

    initialize_database()
    with _get_engine().connect() as connection:
        result = connection.execute(text("SELECT 1")).scalar_one()
        return result == 1


if __name__ == "__main__":
    print("Initializing PostgreSQL database...")
    initialize_database()
    print("Cleaning duplicate alerts...")
    removed = remove_duplicate_alerts()
    print(f"Duplicate alerts removed: {removed}")
    print("Creating unique alert index...")
    create_alert_unique_index()
    print("PostgreSQL setup completed.")
